version: '3'
services:
  db:
    image: postgres:12.5
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "1111:1111"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 30001 -b '0.0.0.0'"
    volumes:
      - .:/app
      - gem_data:/usr/local/bundle
    ports:
      - 30001:30001
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  gem_data:
